open_door:
  name: Open door
  description: Trigger local set.device.opendoor on the configured WelcomeEye device.
  fields:
    entry_id:
      required: false
      selector:
        text:
    door:
      required: false
      selector:
        number:
          min: 1
          max: 4
          mode: box
    lock_number:
      required: false
      selector:
        select:
          options:
            - label: Gâche
              value: 1
            - label: Portail
              value: 2
